执行中任务状态展示及过滤优化
TencentBlueKing/bk-sops pull request #7066
Opened 2023-09-13 02:35 UTC by ZhuoZhuoCrayon

2023-10-11 03:37 UTC, hanshuaikang commented on gcloud/core/apis/drf/viewsets/taskflow.py
> +            if get_task_status_result.get("result"):
关于状态是否为 pending_process的逻辑可以直接在这里处理，在这一步就可以筛选出来 pending_process_taskflow_ids

2023-10-11 03:37 UTC, hanshuaikang commented on gcloud/core/apis/drf/viewsets/taskflow.py
> +            pipeline_instance_id__in=self._fetch_pipeline_instance_ids(statuses=[states.FAILED, states.SUSPENDED])
看我的注释，是 未完成的任务 -（暂停 + 失败的任务)，这里改的好像有问题

2023-10-11 03:37 UTC, hanshuaikang commented on gcloud/core/apis/drf/viewsets/taskflow.py
> +                pipeline_instance_id__in=self._fetch_pipeline_instance_ids(statuses=[states.FAILED])
等待处理应该只存在running状态下的任务，这里可以只拿处于running状态的taskflow_instance

2023-10-11 03:37 UTC, hanshuaikang commented on gcloud/taskflow3/domains/dispatchers/task.py
> +                        (node_output["value"] for node_output in node_outputs if node_output["key"] == "task_id")
这里是取第一个task吗

2023-10-12 08:46 UTC, normal-wls requested changes

2023-10-12 08:46 UTC, normal-wls commented on gcloud/taskflow3/signals/handlers.py
> +        # TODO 发送通知，向上找到根流程，发送通知
这块是否需要确认完再合入

2023-10-12 08:46 UTC, normal-wls commented on pipeline_plugins/components/collections/sites/open/bk/approve/v1_0.py
> +        send_taskflow_message.delay(
目前发送通知的进程配置较低，需要看看这块加上之后是否需要调整进程资源

2023-10-12 08:46 UTC, normal-wls commented on gcloud/taskflow3/celery/tasks.py
> +            dispatcher = TaskCommandDispatcher(
个人认为这个地方不应该有查询任务状态的操作，这个函数的功能抽象未发送任务消息，至于发送什么消息和配置，理论上应该在外部确认好传入

2023-10-12 08:46 UTC, normal-wls commented on gcloud/core/apis/drf/viewsets/taskflow.py
> +        task_status_infos: typing.List[typing.Dict[str, typing.Any]] = concurrent.batch_call(
这块的逻辑可能对 db 有比较大的请求，需要考虑下这块风险

2023-10-12 14:10 UTC, ZhuoZhuoCrayon commented on gcloud/taskflow3/signals/handlers.py
> +        # TODO 发送通知，向上找到根流程，发送通知
> 这块是否需要确认完再合入

已去除，按之前讨论的：独立子流程继承父流程通知配置

2023-10-12 14:11 UTC, ZhuoZhuoCrayon commented on gcloud/core/apis/drf/serilaziers/template.py
> +                else {"success": notify_type, "fail": notify_type, "pending_processing": []}
> {"success": notify_type, "fail": notify_type, "pending_processing": notify_type} 是不是应该跟上面保持一致

已修改

2023-10-12 14:12 UTC, ZhuoZhuoCrayon commented on gcloud/taskflow3/domains/dispatchers/task.py
> +                        (node_output["value"] for node_output in node_outputs if node_output["key"] == "task_id")
> 这里是取第一个task吗

不是，因为输出是 k-v，这里是遍历取第一个名为 `task_id` 的键

2023-10-12 14:12 UTC, ZhuoZhuoCrayon commented on gcloud/core/apis/drf/viewsets/taskflow.py
> +                pipeline_instance_id__in=self._fetch_pipeline_instance_ids(statuses=[states.FAILED])
> 等待处理应该只存在running状态下的任务，这里可以只拿处于running状态的taskflow_instance

逻辑就是这样，`exclude`

2023-10-12 14:22 UTC, ZhuoZhuoCrayon commented on gcloud/core/apis/drf/viewsets/taskflow.py
> +            if get_task_status_result.get("result"):
> 关于状态是否为 pending_process的逻辑可以直接在这里处理，在这一步就可以筛选出来 pending_process_taskflow_ids

不行，`get_task_status` 相对于 DB 查询来说，是一个耗时操作，需要先 DB 过滤出 RUNNING 的流程，再根据 RUNNING 判断最终状态是「等待处理」的流程，这样走 `get_task_status` 的任务数量在一个项目下就非常可控。

2023-10-12 14:23 UTC, ZhuoZhuoCrayon commented on gcloud/core/apis/drf/viewsets/taskflow.py
> +        task_status_infos: typing.List[typing.Dict[str, typing.Any]] = concurrent.batch_call(
> 这块的逻辑可能对 db 有比较大的请求，需要考虑下这块风险

先 DB 过滤出 RUNNING 的流程，再根据 RUNNING 判断最终状态是「等待处理」的流程，这样走 get_task_status 的任务数量在一个项目下就非常可控。

2023-10-12 14:26 UTC, ZhuoZhuoCrayon commented on pipeline_plugins/components/collections/sites/open/bk/approve/v1_0.py
> +        send_taskflow_message.delay(
> 目前发送通知的进程配置较低，需要看看这块加上之后是否需要调整进程资源

后续关注

2023-10-12 14:26 UTC, ZhuoZhuoCrayon commented on gcloud/taskflow3/celery/tasks.py
> +            dispatcher = TaskCommandDispatcher(
> 个人认为这个地方不应该有查询任务状态的操作，这个函数的功能抽象未发送任务消息，至于发送什么消息和配置，理论上应该在外部确认好传入

讨论结论：不做「等待处理」的整体状态判断，节点走到便发通知。
背景：并行网关场景下一分支有失败节点，另一分支有审批/人工确认场景下，任务状态是失败，如果这种场景发通知是否合理。

2023-12-20 09:45 UTC, merged