perf: Added paging function for IP list
TencentBlueKing/bk-sops pull request #7585
Opened 2024-10-15 10:33 UTC by guohelu

2024-10-15 10:33 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-sops?pullRequest=7585) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-sops?pullRequest=7585) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-sops?pullRequest=7585) it.</sub>

2024-10-17 01:55 UTC, normal-wls requested changes

2024-10-17 01:55 UTC, normal-wls commented on gcloud/utils/cmdb.py
> +):
注释补充一下配置参数的格式，给个样例，注意不要用真实数据

2024-10-17 01:55 UTC, normal-wls commented on .pre-commit-config.yaml
> -  - repo: local
这块先不去掉

2024-10-17 01:55 UTC, normal-wls commented on pipeline_plugins/cmdb_ip_picker/query.py
> +    page = {
这个也是一个公共函数，在这里直接分页会影响其他使用场景

2024-10-17 01:55 UTC, normal-wls commented on gcloud/utils/cmdb.py
> +        data = client.cc.list_biz_hosts_topo(kwargs)
改动的点需要覆盖一下单测

2024-10-23 02:35 UTC, closed without merging