Python3.11.10版本及相关依赖包升级
TencentBlueKing/bk-sops pull request #7660
Opened 2024-12-30 08:00 UTC by huangpixu

Python3.11.10版本及相关依赖包升级

2024-12-30 08:00 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-sops?pullRequest=7660) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-sops?pullRequest=7660) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-sops?pullRequest=7660) it.</sub>

2025-01-09 10:11 UTC, normal-wls requested changes

2025-01-17 07:54 UTC, huangpixu commented on requirements.txt
> +# httpsig==1.3.0
已删除

2025-01-17 07:54 UTC, huangpixu commented on requirements.txt
> +# requests_toolbelt==0.9.1
> 如果确定不需要，删掉即可

已删除

2025-01-17 07:55 UTC, huangpixu commented on gcloud/core/views.py
> -    user = LoginRequiredMiddleware().authenticate(request)
> 这里的改动比较奇怪， get_response 指定为 index view 是不是清晰一些

已修改传参get_response=home

2025-01-20 08:59 UTC, normal-wls requested changes

2025-01-20 08:59 UTC, normal-wls commented on gcloud/contrib/collection/migrations/0006_alter_collection_category.py
> +from django.db import migrations, models
看看表变更是否必须

2025-01-20 08:59 UTC, normal-wls commented on gcloud/contrib/operate_record/migrations/0004_alter_taskoperaterecord_operate_source_and_more.py
> +from django.db import migrations, models
看看表变更是否必须

2025-01-20 08:59 UTC, normal-wls commented on gcloud/contrib/appmaker/migrations/0012_alter_appmaker_category.py
> +from django.db import migrations, models
看看表变更是否必须

2025-01-20 09:24 UTC, huangpixu commented on pipeline_plugins/components/query/sites/open/job.py
> +        - TEN_MINUTES_MILLISECONDS * 1,  # 取一天前到一天后这段时间的历史
black代码格式化进行换行了

> 这里为何拆成两行，有点奇怪

2025-01-20 09:51 UTC, huangpixu commented on gcloud/contrib/collection/migrations/0006_alter_collection_category.py
> +from django.db import migrations, models
> 看看表变更是否必须

非升级导致变更，文件已删除

2025-01-20 10:04 UTC, normal-wls approved these changes

2025-01-20 10:05 UTC, merged